import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { ThemeProvider } from "@/lib/ThemeContext";
import { ShoppingListProvider } from "@/context/ShoppingListContext";
import { SearchProvider } from "@/context/SearchContext"; // Import the new SearchProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <ShoppingListProvider>
            <SearchProvider> {/* Wrapping with SearchProvider */}
              <Navbar />
              {children}
            </SearchProvider>
          </ShoppingListProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
